language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-boot-study *
  - mkdir -p deploy
  - mv spring-boot-study.zip deploy/spring-boot-study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jsm-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jsm-springboot-build
    key: spring-boot-study.zip
    application: jsm-springboot-webservice
    deployment_group: jsm-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jsm3467@gmail.com
